### ISSUE TITLE
SepBot broken?

### ISSUE THREAD

**Issue by FreQRiDeR** [nyuszika7h/sepfinder#2]
Not working, latest Telegram update? Is bot down? /start does nothing?

![4CF538E3-1FD7-4CCC-94BD-9F9DF7ACE212](https://user-images.githubusercontent.com/31628763/213516085-49f0ecf8-2be7-4557-aeda-7c6881278250.png)

**Comment by ghost** [comment]
fixed

**Comment by FreQRiDeR** [comment]
Nvm... working now, thanks!
